### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx"

### ISSUE THREAD

**Issue by mrvnklm** [EvodiaAut/vue-progressbar-component#1]
Receiving this error after installing the packge and running npm run watch-poll.

**Comment by EvodiaAut** [comment]
Hi, you need to install https://github.com/vuejs/babel-plugin-transform-vue-jsx

**Comment by mrvnklm** [comment]
I did, but it didnt work

**Comment by EvodiaAut** [comment]
Your project was setup by https://cli.vuejs.org/ ?

**Comment by mrvnklm** [comment]
No, it's a Laravel Nova custom component, the error now:
`Module build failed: Error: Couldn't find preset "stage-2" relative to directory`

**Comment by EvodiaAut** [comment]
Sorry I had nothing to do with laravel nova yet.

Maybe you can find solutions here?

* https://github.com/DigitalCloud/nova-custom-views/issues/7
* https://github.com/sagalbot/vue-select/issues/51

**Comment by mrvnklm** [comment]
Thank you, the 2nd link solved my problem!
